// <auto-generated />
namespace TelerikAngular2.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class visitedPlaceChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(visitedPlaceChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201612262313295_visitedPlaceChanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
